include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    use_key_in_widget_constructors: false
    prefer_final_locals: true
    omit_local_variable_types: true
